package com.yandex.app.api;

public enum Endpoint {

    GET_ALL_TASKS,
    GET_ALL_EPICS,
    GET_ALL_SUBTASKS,
    DELETE_ALL_TASKS,
    DELETE_ALL_EPICS,
    DELETE_ALL_SUBTASKS,
    GET_TASK_BY_ID,
    GET_EPIC_BY_ID,
    GET_SUBTASK_BY_ID,
    CREATE_TASK,
    CREATE_EPIC,
    CREATE_SUBTASK,
    UPDATE_TASK,
    UPDATE_EPIC,
    UPDATE_SUBTASK,
    DELETE_TASK,
    DELETE_EPIC,
    DELETE_SUBTASK,
    GET_ALL_EPIC_SUBTASKS,
    GET_HISTORY,
    GET_PRIORITIZED_TASKS,
    UNKNOWN_ENDPOINT
}
